### PR TITLE
gcc: add a contact page

### PR DESCRIPTION
**Pull request by n1tsu**
/!\ There is actually a Lorem Ipsum waiting for something else to be displayed. This text is here in order to increase height size to avoid bad design (white strip at the bottom. cf image)
mmm3

### CODE REVIEW

**Comment by n1tsu** [comment]
Also translations were not done since it produces weird diff when generating `django.po` file locally.

**Comment by Elfikurr** [comment]
I believe the "weird" generation of the django.po file is because the `--no-wrap` option is not included in the `make tx-push` command.

**Comment by Elfikurr** [comment]
Is there a reason you did not add the "The 2020 team" panel ? We could have it the same as Prologin's website ?
Then we can either redirect to Prologin's website, or make a /team page of our own (with only the team members who participate in GCC ?).

You could add a title, like the one on Prologin's contact page 'About Girls Can Code!' or something like this ? And at the same time add a one line text that could say : 'Girls Can Code! is done by Prologin' (to be developed of course).

The text that will replace the Lorem Ipsum will come soon (once Helloasso is updated ! :D)

Also, you should not load the static module if it is not used !

Apart from that, it looks good, and once the text is ready, should be merged asap ! :)
Thanks !

**Comment by n1tsu** [comment]
> I believe the "weird" generation of the django.po file is because the `--no-wrap` option is not included in the `make tx-push` command.

Indeed, I wanted at the beginning edit generate and edit the file without using `transifex`, and even with the `--no-wrap` option I had some trouble (which might be a mishandling from myself). But I tried with `transifex` and all seems to be ok :)

**Comment by n1tsu** [comment]
> Is there a reason you did not add the "The 2020 team" panel ? We could have it the same as Prologin's website ?

From what I saw there was no 'quick fix' to have the same result. But it sure is a good idea. I can't add it ASAP but we should remember to do it.

> You could add a title, like the one on Prologin's contact page 'About Girls Can Code!' or something like this ? And at the same time add a one line text

Yes good idea :+1: 

> Also, you should not load the static module if it is not used !

Good point :smiley:  I will remove it

**Pull request merged**
